
name: mytrainerapp
description: MyTrainer — Firebase Auth + Firestore + локальні фото (final)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  intl: ^0.20.2
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bg_main.png
    - assets/bg_detail.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#121212"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#121212"
